---
- job:
    name: unit-test
    description: Run Toolbox's unit tests declared in Meson
    timeout: 600
    nodeset:
      nodes:
        - name: ci-node-36
          label: cloud-fedora-36
    pre-run: playbooks/setup-env.yaml
    run: playbooks/unit-test.yaml

- job:
    name: unit-test-migration-path-for-coreos-toolbox
    description: Run Toolbox's unit tests declared in Meson when built with -Dmigration_path_for_coreos_toolbox
    timeout: 600
    nodeset:
      nodes:
        - name: ci-node-36
          label: cloud-fedora-36
    pre-run: playbooks/setup-env-migration-path-for-coreos-toolbox.yaml
    run: playbooks/unit-test.yaml

- job:
    name: system-test-fedora-rawhide
    description: Run Toolbox's system tests in Fedora Rawhide
    timeout: 2700
    nodeset:
      nodes:
        - name: ci-node-rawhide
          label: cloud-fedora-rawhide
    pre-run: playbooks/setup-env.yaml
    run: playbooks/system-test.yaml

- job:
    name: system-test-fedora-36
    description: Run Toolbx's system tests in Fedora 36
    timeout: 1200
    nodeset:
      nodes:
        - name: ci-node-36
          label: cloud-fedora-36
    pre-run: playbooks/setup-env.yaml
    run: playbooks/system-test.yaml

- job:
    name: system-test-fedora-35
    description: Run Toolbox's system tests in Fedora 35
    timeout: 1200
    nodeset:
      nodes:
        - name: ci-node-35
          label: cloud-fedora-35
    pre-run: playbooks/setup-env.yaml
    run: playbooks/system-test.yaml

- project:
    periodic:
      jobs:
        - system-test-fedora-rawhide
        - system-test-fedora-36
        - system-test-fedora-35
    check:
      jobs:
        - unit-test
        - unit-test-migration-path-for-coreos-toolbox
        - system-test-fedora-rawhide
        - system-test-fedora-36
        - system-test-fedora-35
    gate:
      jobs:
        - unit-test
        - unit-test-migration-path-for-coreos-toolbox
        - system-test-fedora-rawhide
        - system-test-fedora-36
        - system-test-fedora-35
